default: &default
  host: localhost
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/puntapie_development

test:
  <<: *default
  database: db/puntapie_test

production:
  <<: *default
  database: db/puntapie
